name: sphinx-build

on:
  push:
    branches:    
      - master

jobs:
  build_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Standard drop-in approach that should work for most people.
    # - uses: ammaraskar/sphinx-action@master
    #   with:
    #     docs-folder: "docs/"

    - uses: wheheohu/sphinx-action@master
      with:
        docs-folder: "docs/"
        
    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/WheheoHu/pybmd.git --branch gh-pages --single-branch gh-pages
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # ===============================

  doc2dash:
    needs: build_push
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: install doc2dash
        run: |
          brew install hynek/tap/doc2dash
          brew install tree

      - name: clone gh-pages branch.
        run: |
          git clone https://github.com/WheheoHu/pybmd.git --branch gh-pages --single-branch gh-pages
      
      - name: doc2dash generate dash docset.
        run: |
          
          tree 
          doc2dash ./gh-pages -n pybmd -i ./docs/dash_docset_icon/DR.png 
          # -d ./gh-pages/dash_doc
          cp -R pybmd.docset ./gh-pages/dash_doc/pybmd.docset
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "update dash docset" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}    

      - name: upload dash doc as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dash_docset
          path: ./gh-pages/dash_doc/pybmd.docset

